export const CarDesingData = {
  title1: "Tasarım",
  title2: "Güvenlik için",
  title3: "Tasarlandı",
  description1: "Güvenlik, her Tesla'nın en önemli",
  description2: "parçasıdır. Araçlarımızı",
  underlinDescription1: "güvenlik",
  underlinDescription2: "standartlarını aşacak şekilde",
  description3: "tasarlıyoruz.",
  description4: "5 Yıldızlı Derecelendirme ve Sınıfının En İyisi ",
  title4: "Güvenlik",
  description5: "Model Y, 2022'de 5 yıldızlı Euro NCAP",
  description6: "güvenlik derecelendirmesi elde etti",
  description7: "ve Küçük Arazi Aracı kategorisinde",
  description8: "Sınıfının En İyisi ödülünü kazandı.",
  lineText1: "Sağlam Yapı",
  lineText2: "Darbe Koruması",
  lineText3: "Alçak Ağırlık Merkezi",
};

export const baseCarDetailsData = {
  baseTitle: "Rubicon Özellikleri",
  cardData1: "Long Range AWD",
  cardData2: "Long Range",
  cardData3: "Long Range",
};

export const carDetailsDataLeft = [
  { id:1,
    title: "Batarya",
    value: "Long Range",
  },
  {id:2,
    title: "Batarya",
    value: "Long Range",
  },
  {id:3,
    title: "Batarya",
    value: "Long Range",
  },
  {id:4,
    title: "Batarya",
    value: "Long Range",
  },
];
export const carDetailsDataRight = [
    { id:1,
        title: "Batarya",
        value: "Long Range",
      },
      {id:2,
        title: "Batarya",
        value: "Long Range",
      },
      {id:3,
        title: "Batarya",
        value: "Long Range",
      },
      {id:4,
        title: "Batarya",
        value: "Long Range",
      },
];
